[base]
port="8082"
default_language="zh"
time_location = "Asia/Chongqing"
[log]
level=0 #0:TRACE 1:DEBUG 2:INFO 3:NOTICE 4:WARN 5:ERROR 7:ACCESS
path="log/"
[database]
driver="mysql"
pretable="account" #数据表前缀名
logfile="D:/data/accountbook/log/db.log"
[[database.accountbook.master]]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
databasename = "accountbook"
[[database.accountbook.slave]]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
databasename = "accountbook"
[[database.accountbook.slave]]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
databasename = "accountbook"
# [cache]
# cacheType = "redis"
#   [cache.redis.0]
#   host = "127.0.0.1"
#   port = "6379"
